### ISSUE TITLE
1.3 browse page error

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#1221] opened 2016-07-29 15:33 UTC
![screenshot from 2016-07-29 09-31-58](https://cloud.githubusercontent.com/assets/1220762/17253773/62618eb0-556f-11e6-9cb9-aaa5e728108e.png)

```
Routing Error
undefined method `partials=' for nil:NilClass

Rails.root: /var/www/sites/hydranorth
Application Trace | Framework Trace | Full Trace

app/controllers/browse_controller.rb:26:in `block in <class:BrowseController>'
blacklight (5.14.0) lib/blacklight/configuration.rb:244:in `configure'
blacklight (5.14.0) lib/blacklight/configurable.rb:40:in `configure_blacklight'
app/controllers/browse_controller.rb:24:in `<class:BrowseController>'
app/controllers/browse_controller.rb:4:in `<top (required)>'
```

**Comment by pgwillia** [comment] 2016-07-29 19:09
Showing up in /var/log/httpd/modsec_audit.log
```
--4f2d8e64-A--
[28/Jul/2016:16:32:19 --0600] V5qH84GA2VgAAFsELUcAAAAD 129.128.217.81 45075 129.128.217.88 80
--4f2d8e64-B--
GET /browse HTTP/1.1
Host: era-test.library.ualberta.ca
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: https://era-test.library.ualberta.ca/
Cookie: __utma=47172282.81970592.1449176163.1450366544.1450369208.13; _ga=GA1.2.81970592.1449176163; __utma=61492728.81970592.1449176163.1469736536.1469745119.15; __utmz=61492728.1449259699.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=87648711.81970592.1449176163.1464894359.1468517603.14; __utmz=87648711.1468517603.14.6.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); km_ai=zlYLNO7IhaM%2FGsMBnolVp%2Ft65TQ%3D; km_uq=; km_lv=x; __unam=94c97c-151c54a4a7f-25b81fcc-22; _vwo_uuid_v2=D7715FA76D428ABFA24AAE4056152C6A|89f05d19072956dd0312c0b25845a715; __atuvc=0%7C26%2C0%7C27%2C1%7C28%2C0%7C29%2C5%7C30; _session_id=a4b28f6289094c990767a467376cc89b; __utmc=61492728; _shibsession_64656661756c7468747470733a2f2f6572612d746573742e6c6962726172792e75616c62657274612e63612f73686962626f6c657468=_611152129faa3d50de53bffaae70ef08; __utmb=61492728.1.10.1469745119; __utmt=1
If-None-Match: W/"8b38636c271d09eae5d677c2deee6c13"
X-Forwarded-Proto: https
X-Forwarded-For: 129.128.46.157

--4f2d8e64-F--
HTTP/1.1 502 Bad Gateway
cache-control: no-cache, no-store, must-revalidate
Content-Length: 54
Status: 502 Bad Gateway
Connection: close
Content-Type: text/html; charset=UTF-8

--4f2d8e64-E--

--4f2d8e64-H--
Stopwatch: 1469745139287636 32172 (- - -)
Stopwatch2: 1469745139287636 32172; combined=30, p1=6, p2=14, p3=2, p4=0, p5=7, sr=0, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.7.3 (http://www.modsecurity.org/).
Server: Apache/2.2.15 (CentOS)
Engine-Mode: "ENABLED"

--4f2d8e64-Z--
```

**Comment by mbarnett** [comment] 2016-07-29 19:39
Error is here: https://github.com/ualbertalib/HydraNorth/blob/master/app/controllers/browse_controller.rb#L26-L27

Specifically:

```ruby 
 #Show gallery view
config.view.gallery.partials = [:index_header, :index]
config.view.slideshow.partials = [:index]
```

I have no idea who added those lines, or what they're supposed to do. As far as I can tell, it's a bug that these 2 lines **ever** worked, because config.view contains neither a ```:gallery``` nor a ```:slideshow``` key -- it's just that in ruby prior to 2.3, some nonsense is returned for missing keys, and the partials key is then defined on that nonsense.

Removing those lines and running a full ```rake spec``` shows absolutely nothing broken, and browsing around myself I saw nothing different. Unless someone knows what those lines are supposed to be doing, I think they're just random broken code that happened to work until ruby 2.3.

**Comment by pgwillia** [comment] 2016-07-29 19:51
@mbarnett I came to the same conclusion. Removing those lines seem to work for me. Still getting lots of warnings, but the browse page is showing
```
.(eval):1: warning: key "resource_type_sim" is duplicated and overwritten on line 1
(eval):1: warning: key "creator_sim" is duplicated and overwritten on line 1
(eval):1: warning: key "subject_sim" is duplicated and overwritten on line 1
(eval):1: warning: key "language_sim" is duplicated and overwritten on line 1
(eval):1: warning: key "hasCollection_ssim" is duplicated and overwritten on line 1
(eval):1: warning: key "year_created_sim" is duplicated and overwritten on line 1
(eval):1: warning: key "publisher_sim" is duplicated and overwritten on line 1
(eval):1: warning: key "contributor_sim" is duplicated and overwritten on line 1
```

**Comment by mbarnett** [comment] 2016-07-29 19:58
Those warnings date back to 2.2 at least. It's an issue in hydra where they're eval-ing large hash literals with the same key in them more than once. 

There's no (afaict) consequences caused by it, and I **believe** it may be fixed in newer versions of the gems.

**Closed** 2016-07-29 20:25 UTC
Labels: bug
