### ISSUE TITLE
Can't change permissions from private to open for migrated item

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#1024] opened 2016-03-17 22:56 UTC
This item - https://era.library.ualberta.ca/files/2801ph22b -  was migrated as private rather than open, although it is acting like open in the interface. Seems to be the only one of its kind; see #730 

Not able to change permissions from private to open. When logged in as admin, you can change the permission setting and save it, and get the action successful message. But if you log out and look at it, it shows as private. Log back in as admin and it is showing as private; change doesn't stick.

Checked another item in this collection, changed permissions from open to private, and back again, and it worked.

**Comment by mbarnett** [comment] 2016-03-18 15:45
Probably a characterization bug: it's stuck in private until characterized, and the characterization must be failing.

**Comment by pbinkley** [comment] 2016-03-30 19:49
Duplicate of #730

**Closed by pbinkley** 2016-03-30 19:49 UTC
Labels: bug
