### ISSUE TITLE
Blank images on home page

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#752] opened 2015-10-15 20:50 UTC
Looks like we might have some blank images rotating through on the home page...

![screen shot 2015-10-15 at 2 49 13 pm](https://cloud.githubusercontent.com/assets/12801010/10527119/fec2aade-734b-11e5-8789-9e05730a47ab.png)

**Comment by sfbetz** [comment] 2015-10-15 20:53
Seems to be related to the counter image? It goes missing when the top images go missing...
![screen shot 2015-10-15 at 2 52 23 pm](https://cloud.githubusercontent.com/assets/12801010/10527204/6c134c6a-734c-11e5-8c58-645602294fb3.png)

**Comment by pbinkley** [comment] 2015-10-15 21:33
I think this is the result of having a session from the old release. If you
refresh, the images come back. (at least they did for me). Closing your
browser and starting fresh may also help.

**Comment by sfbetz** [comment] 2015-10-15 21:47
Yeah - I probably shouldn't quit my day job. Clearing cache resolved issue. Closing!

**Comment by anayram** [comment] 2015-10-16 17:56
Still getting the blank images once in a while.

I have wiped out completely all browsing data in Chrome and Firefox and restarted browsers and sessions in hydranorth. I also tried in another workstation with no browsing data and got the same issue.

Hopefully it is just me but I am reopening this ticket in case someone else can confirm it needs checking. It looks like it is possible to reproduce the problem by refreshing the front page several times.

**Comment by pbinkley** [comment] 2015-10-16 18:11
@anayram  Do the images appear when you refresh the page?

**Comment by pbinkley** [comment] 2015-10-16 18:13
I've moved this to priority:medium because the problem is intermittent, not persistent as it appeared when we first posted it.

**Comment by anayram** [comment] 2015-10-16 18:23
@pbinkley the blank images appeared after refreshing pages multiple times but also occasionally at the first time I accessed HydraNorth from a new browser session with cleared browsing files.

**Comment by johnhuck** [comment] 2015-10-16 18:34
I am also seeing this. I notice it when I logged out on a fresh browser session. Also, I don't know if this is related, but I can't close the "signed out successfully." green box at the same time.

**Comment by pgwillia** [comment] 2015-10-16 18:36
When it occurs 
```
Request URL:https://hydranorth.library.ualberta.ca/assets/application-9ca2665b5fe5a78bde5560531e878943a1c3916b2d4676410087ca79bbacf05f.js
Request Method:GET
Status Code:404 Not Found
```

Perhaps assets the issue.  If not precompiling assets issue, perhaps assets need to be shared between both nodes?

**Comment by pbinkley** [comment] 2015-10-16 18:41
I.e. you might get the page from one node with a js link containing a long
hash that only exists on that node, but the request for the js gets
serviced by the other node? Ugh.

**Comment by pbinkley** [comment] 2015-10-16 18:42
So #756 may have the same cause.

**Comment by anayram** [comment] 2015-10-16 20:30
Looks like this is fixed. Haven't been able to reproduce the problem after release v1.2.0

**Closed** 2015-10-19 20:03 UTC
Labels: bug, priority:medium
