### ISSUE TITLE
Admin can purge/restore items

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#96] opened 2015-02-17 18:08 UTC
As admin, I want to be able to delete or purge items from Hydra North, but I want users to be able only to delete them (i.e. leave them in a recoverable state), so that items are not lost due to errors by users size:medium priority:high sprint:9

**Comment by pbinkley** [comment] 2016-03-02 20:36
Not needed. Dupe of #33 .

**Closed by pbinkley** 2016-03-02 20:36 UTC
Labels: priority:TBD, size:TBD, wontfix
