### ISSUE TITLE
Community and Collection disappear on form for item edit

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1118] opened 2016-05-20 15:55 UTC
I noticed this yesterday and thought it was my fault, but now I've replicated the problem. 

For example, I just clicked on 'edit' as ERA Administrator for this item:
https://era.library.ualberta.ca/files/bzg64tm03g#.Vz8yRrgrJaQ

It used to be in ERA Processing Community
https://era.library.ualberta.ca/collections/44558r79q

in the Articles collection.
https://era.library.ualberta.ca/collections/44558s29q

I cancelled edit and the Community and Collection are still there. But this is something that will be very problematic to users, and I'm worried about the data and whether the integrity of those associations are in place.

**Comment by mbarnett** [comment] 2016-05-20 18:04
@pbinkley The good news is that this isn't related to older issues we've had with collections/communities not sticking, so that's progress.

The bad news is that this is all very odd:

Here's the item in Fedora:

```ruby
> GenericFile.find('bzg64tm03g')
=> #<GenericFile id: "bzg64tm03g", mime_type: "image/jpeg", format_label: ["JPEG File Interchange Format"], file_size: ["18060"], last_modified: ["2016:04:25 09:08:05-06:00"], filename: ["many_users.jpg"], original_checksum: ["85ded56be315736fcc69df7b18cae413"], rights_basis: [], copyright_basis: [], copyright_note: [], well_formed: ["true"], valid: ["true"], status_message: [], file_title: [], file_author: [], page_count: [], file_language: [], word_count: [], character_count: [], paragraph_count: [], line_count: [], table_count: [], graphics_count: [], byte_order: ["big endian"], compression: ["JPEG (old-style)"], color_space: ["YCbCr"], profile_name: [], profile_version: [], orientation: [], color_map: [], image_producer: [], capture_device: [], scanning_software: [], exif_version: [], gps_timestamp: [], latitude: [], longitude: [], character_set: [], markup_basis: [], markup_language: [], bit_depth: [], channels: [], data_format: [], offset: [], frame_rate: [], label: "many_users.jpg", depositor: "leahv@ualberta.ca", relative_path: "", import_url: nil, part_of: [], resource_type: ["Book Chapter"], title: ["test1"], creator: ["vanderjagt"], contributor: [], description: [], rights: "", publisher: [], date_created: "", date_modified: Mon, 25 Apr 2016 15:07:58 +0000, subject: ["test subject"], language: "English", identifier: [], related_url: "", source: "", proxy_depositor: nil, on_behalf_of: nil, date_uploaded: Mon, 25 Apr 2016 15:07:58 +0000, license: "http://creativecommons.org/licenses/by-sa/4.0/", trid: nil, ser: nil, temporal: [], spatial: [], is_version_of: "", unicorn: nil, fedora3uuid: nil, fedora3handle: nil, ingestbatch: nil, hasCollection: [], belongsToCommunity: [], hasCollectionId: [], year_created: nil, remote_resource: nil, degree_grantor: nil, dissertant: nil, supervisor: [], committee_member: [], department: [], specialization: nil, date_submitted: Mon, 25 Apr 2016 15:07:58 +0000, date_accepted: nil, graduation_date: nil, alternative_title: [], thesis_name: nil, thesis_level: nil, proquest: nil, abstract: nil, batch_id: "fx719q16z", embargo_id: nil, lease_id: nil>
```
hasCollection, hasCollectionId, and belongsToCommunity are all empty, and they definitely shouldn't be. This is why the Community and Collection dropdowns aren't populated on the item edit screen, which works off of the Fedora record.

Here's the Solr data for the item:

```ruby
{"responseHeader"=>{"status"=>0, "QTime"=>12, "params"=>{"q"=>"id:bzg64tm03g", "fl"=>"*", "wt"=>"ruby"}}, "response"=>{"numFound"=>1, "start"=>0, "maxScore"=>11.495128, "docs"=>[{"system_create_dtsi"=>"2016-04-25T15:07:58Z", "system_modified_dtsi"=>"2016-04-25T15:09:15Z", "active_fedora_model_ssi"=>"GenericFile", "has_model_ssim"=>["GenericFile"], "id"=>"bzg64tm03g", "object_profile_ssm"=>["{\"id\":\"bzg64tm03g\",\"mime_type\":\"image/jpeg\",\"format_label\":[\"JPEG File Interchange Format\"],\"file_size\":[\"18060\"],\"last_modified\":[\"2016:04:25 09:08:05-06:00\"],\"filename\":[\"many_users.jpg\"],\"original_checksum\":[\"85ded56be315736fcc69df7b18cae413\"],\"rights_basis\":[],\"copyright_basis\":[],\"copyright_note\":[],\"well_formed\":[\"true\"],\"valid\":[\"true\"],\"status_message\":[],\"file_title\":[],\"file_author\":[],\"page_count\":[],\"file_language\":[],\"word_count\":[],\"character_count\":[],\"paragraph_count\":[],\"line_count\":[],\"table_count\":[],\"graphics_count\":[],\"byte_order\":[\"big endian\"],\"compression\":[\"JPEG (old-style)\"],\"color_space\":[\"YCbCr\"],\"profile_name\":[],\"profile_version\":[],\"orientation\":[],\"color_map\":[],\"image_producer\":[],\"capture_device\":[],\"scanning_software\":[],\"exif_version\":[],\"gps_timestamp\":[],\"latitude\":[],\"longitude\":[],\"character_set\":[],\"markup_basis\":[],\"markup_language\":[],\"bit_depth\":[],\"channels\":[],\"data_format\":[],\"offset\":[],\"frame_rate\":[],\"label\":\"many_users.jpg\",\"depositor\":\"leahv@ualberta.ca\",\"relative_path\":\"\",\"import_url\":null,\"part_of\":[],\"resource_type\":[\"Book Chapter\"],\"title\":[\"test1\"],\"creator\":[\"vanderjagt\"],\"contributor\":[],\"description\":[],\"rights\":\"\",\"publisher\":[],\"date_created\":\"\",\"date_modified\":\"2016-04-25T15:07:58.327+00:00\",\"subject\":[\"test subject\"],\"language\":\"English\",\"identifier\":[],\"related_url\":\"\",\"source\":\"\",\"proxy_depositor\":null,\"on_behalf_of\":null,\"date_uploaded\":\"2016-04-25T15:07:58.327+00:00\",\"license\":\"http://creativecommons.org/licenses/by-sa/4.0/\",\"trid\":null,\"ser\":null,\"temporal\":[],\"spatial\":[],\"is_version_of\":\"\",\"unicorn\":null,\"fedora3uuid\":null,\"fedora3handle\":null,\"ingestbatch\":null,\"hasCollection\":[\"Articles\"],\"belongsToCommunity\":[\"44558r79q\"],\"hasCollectionId\":[\"44558s29q\"],\"year_created\":null,\"remote_resource\":null,\"degree_grantor\":null,\"dissertant\":null,\"supervisor\":[],\"committee_member\":[],\"department\":[],\"specialization\":null,\"date_submitted\":\"2016-04-25T15:07:58.327+00:00\",\"date_accepted\":null,\"graduation_date\":null,\"alternative_title\":[],\"thesis_name\":null,\"thesis_level\":null,\"proquest\":null,\"abstract\":null,\"batch_id\":\"fx719q16z\",\"embargo_id\":null,\"lease_id\":null}"], "mime_type_tesim"=>["image/jpeg"], "depositor_ssim"=>["leahv@ualberta.ca"], "depositor_tesim"=>["leahv@ualberta.ca"], "resource_type_tesim"=>["Book Chapter"], "title_tesim"=>["test1"], "creator_tesim"=>["vanderjagt"], "date_modified_dtsi"=>"2016-04-25T15:07:58Z", "subject_tesim"=>["test subject"], "language_tesim"=>["English"], "isPartOf_ssim"=>["fx719q16z"], "date_uploaded_dtsi"=>"2016-04-25T15:07:58Z", "license_tesim"=>["http://creativecommons.org/licenses/by-sa/4.0/"], "hasCollection_ssim"=>["Articles"], "hasCollection_tesim"=>["Articles"], "belongsToCommunity_ssim"=>["44558r79q"], "belongsToCommunity_tesim"=>["44558r79q"], "hasCollectionId_ssim"=>["44558s29q"], "hasCollectionId_tesim"=>["44558s29q"], "date_submitted_dtsim"=>["2016-04-25T15:07:58Z"], "label_tesim"=>["many_users.jpg"], "file_format_tesim"=>["jpeg (JPEG File Interchange Format)"], "file_size_is"=>18060, "read_access_group_ssim"=>["public"], "edit_access_person_ssim"=>["leahv@ualberta.ca"], "_version_"=>1532595490745483264, "timestamp"=>"2016-04-25T15:09:16.963Z"}]}, "facet_counts"=>{"facet_queries"=>{}, "facet_fields"=>{"active_fedora_model_ssi"=>["GenericFile", 1], "object_type_si"=>[]}, "facet_dates"=>{}, "facet_ranges"=>{}, "facet_intervals"=>{}}, "spellcheck"=>{"suggestions"=>["correctlySpelled", true]}}
```

They're totally decohered. The collection data is correct here, which is why on pages driven by Solr and not Fedora, they're showing up correctly

He's the "Era Processing" community in Fedora:

```ruby
> Collection.find('4455879q')
=> <Collection id: "44558r79q", license: nil, fedora3uuid: "uuid:4d49dbe7-50ec-4eb5-bbce-6447f3ca0294", fedora3handle: nil, belongsToCommunity: [], is_community: nil, is_official: nil, is_admin_set: nil, hasCollectionMember: ["b7p88cg629", "bb8515n41r", "s1784p56c", "qf85nc540"], depositor: "eraadmi@ualberta.ca", part_of: [], contributor: [], creator: ["ERA Administrator"], title: "ERA Processing", description: "This is a working space community for data preparation and is for the use of ERA development staff only.", publisher: [], date_created: [], date_uploaded: nil, date_modified: nil, subject: [], language: [], rights: [], resource_type: [], identifier: [], based_near: [], tag: [], related_url: []>
```

For some reason, is_community and is_official are nil, meaning as far as Hydranorth is concerned this isn't a Community.

Also, bzg64tm03g doesn't appear in hasCollectionMember, when it should.

Now, here's the Solr document for the Community:

```ruby
 {"responseHeader"=>{"status"=>0, "QTime"=>13, "params"=>{"q"=>"id:44558r79q", "fl"=>"*", "wt"=>"ruby"}}, "response"=>{"numFound"=>1, "start"=>0, "maxScore"=>10.846084, "docs"=>[{"system_create_dtsi"=>"2015-10-01T16:51:32Z", "system_modified_dtsi"=>"2016-04-27T21:56:52Z", "active_fedora_model_ssi"=>"Collection", "has_model_ssim"=>["Collection"], "id"=>"44558r79q", "object_profile_ssm"=>["{\"id\":\"44558r79q\",\"license\":null,\"fedora3uuid\":\"uuid:4d49dbe7-50ec-4eb5-bbce-6447f3ca0294\",\"fedora3handle\":null,\"belongsToCommunity\":[],\"is_community\":true,\"is_official\":true,\"is_admin_set\":false,\"hasCollectionMember\":[\"b7p88cg629\",\"bb8515n41r\",\"s1784p56c\",\"qf85nc540\"],\"depositor\":\"eraadmi@ualberta.ca\",\"part_of\":[],\"contributor\":[],\"creator\":[\"ERA Administrator\"],\"title\":\"ERA Processing\",\"description\":\"This is a working space community for data preparation and is for the use of ERA development staff only.\",\"publisher\":[],\"date_created\":[],\"date_uploaded\":null,\"date_modified\":null,\"subject\":[],\"language\":[],\"rights\":[],\"resource_type\":[],\"identifier\":[],\"based_near\":[],\"tag\":[],\"related_url\":[]}"], "fedora3uuid_ssim"=>["uuid:4d49dbe7-50ec-4eb5-bbce-6447f3ca0294"], "fedora3uuid_tesim"=>["uuid:4d49dbe7-50ec-4eb5-bbce-6447f3ca0294"], "is_community_bsi"=>true, "is_official_bsi"=>true, "is_admin_set_bsi"=>false, "depositor_ssim"=>["eraadmi@ualberta.ca"], "depositor_tesim"=>["eraadmi@ualberta.ca"], "creator_tesim"=>["ERA Administrator"], "title_tesim"=>["ERA Processing"], "description_tesim"=>["This is a working space community for data preparation and is for the use of ERA development staff only."], "read_access_group_ssim"=>["public"], "edit_access_group_ssim"=>["registered"], "edit_access_person_ssim"=>["eraadmi@ualberta.ca"], "_version_"=>1532802328963317760, "timestamp"=>"2016-04-27T21:56:53.272Z"}]}, "facet_counts"=>{"facet_queries"=>{}, "facet_fields"=>{"active_fedora_model_ssi"=>["Collection", 1], "object_type_si"=>[]}, "facet_dates"=>{}, "facet_ranges"=>{}, "facet_intervals"=>{}}, "spellcheck"=>{"suggestions"=>["correctlySpelled", true]}}
```

Decohered again. It's a community, it's official, and it has the right members.

Here's the 'Articles' collection:

```ruby
> Collection.find('44558s29q')
=> <Collection id: "44558s29q", license: nil, fedora3uuid: "uuid:225a882d-e409-4680-a2fd-6678730d024e", fedora3handle: nil, belongsToCommunity: [], is_community: nil, is_official: nil, is_admin_set: nil, hasCollectionMember: [#<ActiveTriples::Resource:0x295e820(#<ActiveTriples::Resource:0x000000052bd040>)>, #<ActiveTriples::Resource:0x2950aa4(#<ActiveTriples::Resource:0x000000052a1548>)>, #<ActiveTriples::Resource:0x293dc74(#<ActiveTriples::Resource:0x0000000527b8e8>)>, "bvx021f15c", "b8336h196b", "2514np20z", "8w32r846q", "bzg64tm03g"], depositor: "eraadmi@ualberta.ca", part_of: [], contributor: [], creator: ["ERA Administrator"], title: "Articles", description: "", publisher: [], date_created: [], date_uploaded: nil, date_modified: nil, subject: [], language: [], rights: [], resource_type: [], identifier: [], based_near: [], tag: [], related_url: []>
```

bzg64tm03g is listed in hasCollectionMember. But belongsToCommunity is empty, when it should contain 4455879q.

The Solr Document for the collection:

```ruby
=> {"responseHeader"=>{"status"=>0, "QTime"=>16, "params"=>{"q"=>"id:44558s29q", "fl"=>"*", "wt"=>"ruby"}}, "response"=>{"numFound"=>1, "start"=>0, "maxScore"=>10.846084, "docs"=>[{"system_create_dtsi"=>"2015-10-01T16:58:39Z", "system_modified_dtsi"=>"2016-04-25T15:09:14Z", "active_fedora_model_ssi"=>"Collection", "has_model_ssim"=>["Collection"], "id"=>"44558s29q", "object_profile_ssm"=>["{\"id\":\"44558s29q\",\"license\":null,\"fedora3uuid\":\"uuid:225a882d-e409-4680-a2fd-6678730d024e\",\"fedora3handle\":null,\"belongsToCommunity\":[\"44558r79q\"],\"is_community\":false,\"is_official\":true,\"is_admin_set\":false,\"hasCollectionMember\":[{\"id\":\"http://mycombe.library.ualberta.ca:8080/fedora/rest/prod/98/80/vs/30/9880vs30g\"},{\"id\":\"http://mycombe.library.ualberta.ca:8080/fedora/rest/prod/bd/f6/5v/78/bdf65v785t\"},{\"id\":\"http://mycombe.library.ualberta.ca:8080/fedora/rest/prod/br/j4/30/45/brj430453v\"},\"bvx021f15c\",\"b8336h196b\",\"2514np20z\",\"8w32r846q\",\"bzg64tm03g\"],\"depositor\":\"eraadmi@ualberta.ca\",\"part_of\":[],\"contributor\":[],\"creator\":[\"ERA Administrator\"],\"title\":\"Articles\",\"description\":\"\",\"publisher\":[],\"date_created\":[],\"date_uploaded\":null,\"date_modified\":null,\"subject\":[],\"language\":[],\"rights\":[],\"resource_type\":[],\"identifier\":[],\"based_near\":[],\"tag\":[],\"related_url\":[]}"], "fedora3uuid_ssim"=>["uuid:225a882d-e409-4680-a2fd-6678730d024e"], "fedora3uuid_tesim"=>["uuid:225a882d-e409-4680-a2fd-6678730d024e"], "belongsToCommunity_ssim"=>["44558r79q"], "belongsToCommunity_tesim"=>["44558r79q"], "is_community_bsi"=>false, "is_official_bsi"=>true, "is_admin_set_bsi"=>false, "depositor_ssim"=>["eraadmi@ualberta.ca"], "depositor_tesim"=>["eraadmi@ualberta.ca"], "creator_tesim"=>["ERA Administrator"], "title_tesim"=>["Articles"], "read_access_group_ssim"=>["public"], "edit_access_group_ssim"=>["registered"], "edit_access_person_ssim"=>["eraadmi@ualberta.ca"], "_version_"=>1532595488585416704, "timestamp"=>"2016-04-25T15:09:14.909Z"}]}, "facet_counts"=>{"facet_queries"=>{}, "facet_fields"=>{"active_fedora_model_ssi"=>["Collection", 1], "object_type_si"=>[]}, "facet_dates"=>{}, "facet_ranges"=>{}, "facet_intervals"=>{}}, "spellcheck"=>{"suggestions"=>["correctlySpelled", true]}}
```

Decohered. BelongsToCommunity is set properly here.

The Community and Collection Fedora objects are almost totally hollowed out -- modified dates are missing and descriptions are gone, vs the Solr object.

@pbinkley I don't see how this level of alteration of the Fedora object is possible without updating Solr is possible going through ActiveFedora. Is it possible that some of the batch work you were doing directly to Fedora had the unintentional impact of clobering this data?

If that's not it I'm not even sure where to start looking for things that could have caused this, frankly. It shouldn't be possible, anywhere in the application, to change data in such a way that it doesn't get reflected in either Solr or Fedora

**Comment by pbinkley** [comment] 2016-05-20 18:16
I don't find it in the production.log on bournemouth, which is where I was working on collections and communities, or in the logs of the fedora rest api stuff I run from my workstation. It's possible that @weiweishi 's audit repair work touched it (though it touched many many objects so you'd think we would see this problem everywhere if that were the cause). 

As discussed just now I'll repair this item manually in the console and see if we can recreate the problem.

**Comment by pgwillia** [comment] 2016-05-20 21:25
https://github.com/ualbertalib/HydraNorth/pull/1087

**Comment by mbarnett** [comment] 2016-05-20 21:54
The fix has been deployed, and I've just verified that when editing https://era.library.ualberta.ca/files/bzg64tm03g the Collection and Community dropdowns are populating correctly

**Closed** 2016-06-20 15:53 UTC
Labels: bug, priority:high
