### ISSUE TITLE
Search using noid exhibiting strange behaviour

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#1031] opened 2016-03-29 14:57 UTC
Just noticed this behaviour this morning and hope others can replicate it. I am working through a list of noids and it doesn't happen with all of them. And sometimes it depends on whether you search from the home page or the search box at the top right of a results page.

For example: I searched 5425kc31j from the home page and got the 'no results found' message which is what I would expect if the item wasn't there

Next: I searched 2227mr07z from the home page and got a 'sorry, I don't understand your search' message. I searched for the same noid again from the home page and received the same error.

Next: I searched 6t053g86j from the home page and got the 'sorry, I don't understand your search' message. I searched the same noid again from the home page and was taken to a results page with the item listed.

Next: From that item page I searched 9c67wn18h via the search box at the top right and got the 'sorry, I don't understand your search' message. This appears on the home page and when I searched the same noid via the home page search I was taken to the item page.

**Comment by leahvanderjagt** [comment] 2016-03-29 15:01
I've had a user report with a similar problem as well. this one has a
handle: http://hdl.handle.net/10402/era.40993

The result is 'we're sorry, but something went wrong'.



On Tue, Mar 29, 2016 at 8:57 AM, Sharon Farnel <notifications@github.com>
wrote:

> Just noticed this behaviour this morning and hope others can replicate it.
> I am working through a list of noids and it doesn't happen with all of
> them. And sometimes it depends on whether you search from the home page or
> the search box at the top right of a results page.
>
> For example: I searched 5425kc31j from the home page and got the 'no
> results found' message which is what I would expect if the item wasn't there
>
> Next: I searched 2227mr07z from the home page and got a 'sorry, I don't
> understand your search' message. I searched for the same noid again from
> the home page and received the same error.
>
> Next: I searched 6t053g86j from the home page and got the 'sorry, I don't
> understand your search' message. I searched the same noid again from the
> home page and was taken to a results page with the item listed.
>
> Next: From that item page I searched 9c67wn18h via the search box at the
> top right and got the 'sorry, I don't understand your search' message. This
> appears on the home page and when I searched the same noid via the home
> page search I was taken to the item page.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1031>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by leahvanderjagt** [comment] 2016-03-29 15:02
I think the whole application is unstable, I'm encountering many errors
clicking on various links. Submitting a HelpDesk ticket now.

On Tue, Mar 29, 2016 at 9:01 AM, Leah Vanderjagt <leahv@ualberta.ca> wrote:

> I've had a user report with a similar problem as well. this one has a
> handle: http://hdl.handle.net/10402/era.40993
>
> The result is 'we're sorry, but something went wrong'.
>
>
>
> On Tue, Mar 29, 2016 at 8:57 AM, Sharon Farnel <notifications@github.com>
> wrote:
>
>> Just noticed this behaviour this morning and hope others can replicate
>> it. I am working through a list of noids and it doesn't happen with all of
>> them. And sometimes it depends on whether you search from the home page or
>> the search box at the top right of a results page.
>>
>> For example: I searched 5425kc31j from the home page and got the 'no
>> results found' message which is what I would expect if the item wasn't there
>>
>> Next: I searched 2227mr07z from the home page and got a 'sorry, I don't
>> understand your search' message. I searched for the same noid again from
>> the home page and received the same error.
>>
>> Next: I searched 6t053g86j from the home page and got the 'sorry, I don't
>> understand your search' message. I searched the same noid again from the
>> home page and was taken to a results page with the item listed.
>>
>> Next: From that item page I searched 9c67wn18h via the search box at the
>> top right and got the 'sorry, I don't understand your search' message. This
>> appears on the home page and when I searched the same noid via the home
>> page search I was taken to the item page.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ualbertalib/HydraNorth/issues/1031>
>>
>
>
>
> --
> ___________________________________________________________
>
>
>
>
> *Leah VanderjagtDigital Repository Services Librarian University of
> Albertat. 780.492.3851 <780.492.3851> *
> *leahv@ualberta.ca <leahv@ualberta.ca> *
>
>


-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by weiweishi** [comment] 2016-03-29 15:31
Is it possible that one of the solr cloud shards is having problem?
Ccing Henry so he has more information.

Weiwei

On Tuesday, March 29, 2016, leahvanderjagt <notifications@github.com> wrote:

> I think the whole application is unstable, I'm encountering many errors
> clicking on various links. Submitting a HelpDesk ticket now.
>
> On Tue, Mar 29, 2016 at 9:01 AM, Leah Vanderjagt <leahv@ualberta.ca
> <javascript:_e(%7B%7D,'cvml','leahv@ualberta.ca');>> wrote:
>
> > I've had a user report with a similar problem as well. this one has a
> > handle: http://hdl.handle.net/10402/era.40993
> >
> > The result is 'we're sorry, but something went wrong'.
> >
> >
> >
> > On Tue, Mar 29, 2016 at 8:57 AM, Sharon Farnel <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> >> Just noticed this behaviour this morning and hope others can replicate
> >> it. I am working through a list of noids and it doesn't happen with all
> of
> >> them. And sometimes it depends on whether you search from the home page
> or
> >> the search box at the top right of a results page.
> >>
> >> For example: I searched 5425kc31j from the home page and got the 'no
> >> results found' message which is what I would expect if the item wasn't
> there
> >>
> >> Next: I searched 2227mr07z from the home page and got a 'sorry, I don't
> >> understand your search' message. I searched for the same noid again from
> >> the home page and received the same error.
> >>
> >> Next: I searched 6t053g86j from the home page and got the 'sorry, I
> don't
> >> understand your search' message. I searched the same noid again from the
> >> home page and was taken to a results page with the item listed.
> >>
> >> Next: From that item page I searched 9c67wn18h via the search box at the
> >> top right and got the 'sorry, I don't understand your search' message.
> This
> >> appears on the home page and when I searched the same noid via the home
> >> page search I was taken to the item page.
> >>
> >> —
> >> You are receiving this because you are subscribed to this thread.
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/ualbertalib/HydraNorth/issues/1031>
> >>
> >
> >
> >
> > --
> > ___________________________________________________________
> >
> >
> >
> >
> > *Leah VanderjagtDigital Repository Services Librarian University of
> > Albertat. 780.492.3851 <780.492.3851> *
> > *leahv@ualberta.ca <javascript:_e(%7B%7D,'cvml','leahv@ualberta.ca');> <
> leahv@ualberta.ca <javascript:_e(%7B%7D,'cvml','leahv@ualberta.ca');>> *
> >
> >
>
>
> --
> ___________________________________________________________
>
>
>
>
> *Leah VanderjagtDigital Repository Services Librarian University of
> Albertat. 780.492.3851 *
> *leahv@ualberta.ca <javascript:_e(%7B%7D,'cvml','leahv@ualberta.ca');> <
> leahv@ualberta.ca <javascript:_e(%7B%7D,'cvml','leahv@ualberta.ca');>> *
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1031#issuecomment-202942100>
>


-- 

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment] 2016-03-29 16:08
The issue is solved by restarting zookeeper.  Helpdesk ticket will have more information. Close the issue.

**Closed by weiweishi** 2016-03-29 16:08 UTC
Labels: bug
