### ISSUE TITLE
Error message clicking on "edit selected" 

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#489] opened 2015-07-07 22:45 UTC
Selected all files and clicked here:

![edit selected](https://cloud.githubusercontent.com/assets/12801010/8559208/8704dabc-24c7-11e5-87d4-f40b92782170.png)

Error message:

![my files - edit selected](https://cloud.githubusercontent.com/assets/12801010/8559205/7fb3beae-24c7-11e5-9629-5779ed793a20.png)

**Comment by pbinkley** [comment] 2015-11-09 17:20
Duplicate of #783

**Closed by pbinkley** 2015-11-09 17:20 UTC
Labels: bug
