### ISSUE TITLE
Error depositing Computing Science technical report

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#920] opened 2016-01-13 19:49 UTC
1) My Dashboard > My Files & Collections
When I tried to edit the technical report by clicking the checkbox and using the "Edit selected" button, I got a "We're sorry, something went wrong" message. But using the "Select an action > Edit File" dropdown worked fine. (screenshots 1 & 2)
![screen shot 2016-01-13 at 11 45 30 am](https://cloud.githubusercontent.com/assets/1220762/12305832/e8e052b8-b9f3-11e5-86db-3b3da772a563.png)
![screen shot 2016-01-13 at 11 58 51 am](https://cloud.githubusercontent.com/assets/1220762/12305850/f4a52b00-b9f3-11e5-8ddd-b0ed7c2eba74.png)

2) Editing a document description
I couldn't find the "Technical Report" collection in the drop down. When I was adding the document, when I chose "Department of Computing Science" as the Community, the Collections drop down narrowed so only "Technical Report" was shown. It looks like now I see all Collections but the closest I found was "Other Technical Reports"... is that the one I want? (screenshot 3)
![screen shot 2016-01-13 at 11 52 27 am](https://cloud.githubusercontent.com/assets/1220762/12305840/eed5a6f0-b9f3-11e5-8a95-f72540b92790.png)

**Comment by pgwillia** [comment] 2016-01-13 19:51
Also, it looks like the "Computing science technical report ID" field isn't saving.

**Comment by weiweishi** [comment] 2016-01-18 17:29
I think when users are uploading computing sciences technical report/structural engineering report we should disable the community/collection selection portion, as they have the default community/collection to deposit.

**Comment by pbinkley** [comment] 2016-02-22 22:35
Batch edit problem is duplicate of #783; we think the communities/collection problem is fixed; but the technical report id not being saved needs to be checked.

**Comment by weiweishi** [comment] 2016-02-22 22:40
no deposit can be made (probably because it can't handle the report Id? ) - so no data need to be fixed.

**Comment by pbinkley** [comment] 2016-05-09 19:34
replaced by #783 and #1088

**Closed by pbinkley** 2016-05-09 19:34 UTC
Labels: bug, priority:high, size:TBD
