### ISSUE TITLE
8.5 Lock Theses after ingest

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#25] opened 2015-01-05 23:06 UTC
as admin, I want to be able to prevent owners of items in certain collections or of certain item types from editing the files or metadata for those items, so that students can't change their thesis metadata after it has been approved by Grad Studies (probably can be done with permissions at file/datastream level) size:medium priority:high

**Comment by pgwillia** [comment] 2015-01-07 17:48
Comments inline:

On Tue, Jan 6, 2015 at 4:29 PM, Peter Binkley <notifications@github.com>
wrote:

> My view: for what's in scope at the moment (current ERA functionality),
> locking at the collection level is sufficient, and the button isn't
> strictly necessary even for that since we're talking about only one
> collection.


Let me think through how this would work without a button. I assumed that
the prerequisite to this story was that the theses had been uploaded and
assigned to a collection.  I also assumed that the "depositor" had been
initialized as the student who wrote the thesis and that the student is a
user of HydraNorth. I assumed that locking permissions to a file is
something that an administrator would want to happen (or not happen) based
on taking an action (hence the buttons).

Challenging assumptions leads to a few new ideas:

   1. maybe the student is creator only in metadata not in user
   permissions? => this implies
      - accounts are not created for thesis authors as part of the ingest
      of new or old theses (if they do not already exist as part of user
      migration)
      - an admin user retains depositor status on the file
      - the student wouldn't be able to highlight on user profile without
      contacting the admin requesting permissions to their thesis
      2. maybe read/write permissions are over-ridden for certain resource
   type (=Thesis) in the file's metadata
      - should this be configured at application startup or dynamically
      from within the application, or should it be the application default?
      3. maybe the collection comes first. Then anything added to the
   collection get its permissions changed at the point it is added.
      - 'Thesis' collection is added when application is deployed using
      seed.rb
      - Only admins have access to include/exclude works from 'Thesis'
      collections
      - 'Thesis' collection cannot be removed



> However, I'm willing to take on targets of opportunity, especially where
> they allow us to explore and show off features of Hydra that we expect to
> be important to us, in this case the integration with Fedora permissions.
> And especially especially if they are features we might contribute back. Do
> you think this basket of back-end and front-end changes can be packaged
> generically enough to be of use to other Sufia implementors without a lot
> of extra work? I suppose others might want to associate the power to lock
> with other user groups, for example.
>

I could submit the changes in a pull request to sufia codebase.  It would
be hard to know what 'generically enough' would look like until after
submitting the changes to the community and asking for feedback. I think
what I would do is to try to make our implementation collection/work
agnostic and name this permission lock_edits using CanCan which would allow
any Hydra project to assign that permission to any group they like
following the suggestions in the Hydra Role Mangement gem.

Down the road I can imagine us wanting to grant this power over items in a
> given collection to an "owner" of that collection, but my sense is that we
> should wait for that need to arise in a user story before we pursue it.
>

Thanks. Admin only confirmed.

Owners of a collection can add works that don't belong to themselves. Any
user can create a collection.  I think giving the power of locking edits to
any user would be troublesome. However, locking edits to works on the "My
Files" dashboard might be useful. But that's for another time.

**Comment by pbinkley** [comment] 2015-01-07 19:23
Option 3 is the one I imagined (the thesis collection is a "locking
collection", in which any new item is automatically locked). Items will
only be added to this collection by the automated process that pulls theses
from old ERA (which will live on to provide the thesis deposit workflow if
necessary) or from a new workflow engine to be provided by Grad Studies
(presumably Alfresco, and presumably not in place before Hydra launch, but
both of those assumptions may be overridden by events).

When we come to consider locks in other contexts we'll have to think about
the case of co-authors locking each other out, but that's for the future.

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pgwillia** [comment] 2015-01-19 22:47
There will be two thesis collections: http://hdl.handle.net/10402/era.2
* Theses and Dissertations Spring 2009 to present
  * We will still be getting a feed in from FGSR with the ETD-MS elements for the '2009 to present' collection and they should still be protected from editing or deletion
* Theses and Dissertations to Spring 2009
  * The legacy collection has admin as an owner for all the items because we only add items in batches (or rarely, upon user request, like Peter's request this morning :). @leahvanderjagt will need to make a decision on whether a user can deposit or edit items in this collection.

**Comment by pbinkley** [comment] 2015-01-19 22:58
(Just to clarify: if I ever uploaded it, I wouldn't want my dissertation to
go into the "Theses and Dissertations to Spring 2009" collection, which is
just U of A; I would want it to be a personal item, that happened to have
type "thesis").

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment] 2015-02-13 21:29
Note: we want to be sure that deleting a collection does not delete the items in the collection

**Comment by pgwillia** [comment] 2015-02-17 18:17
There will only be one Thesis collection. This will be accomplished by #88

**Closed by pgwillia** 2015-02-17 18:17 UTC
Labels: enhancement
