### ISSUE TITLE
Maintain timestamp / datestamp for original upload into ERA?

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#574] opened 2015-09-01 00:19 UTC
Follow up from conversation with Leah - she wanted to ensure that we maintain (either in the item record, or other place in metadata) information about the time and date of an item's original upload to ERA.  Based on what I see in Hydra item record, the date of upload is the date of migration into Hydra and not the date the item was originally added to ERA (which will predate migration for all items that are migrated). Can anyone advise on if / how that metadata is retained? 

Also important for Leah was maintaining the record of thesis workflow transactions (eg date thesis was submitted, revised, archived, and by whom etc). Will that information also be migrated?

**Comment by sfarnel** [comment] 2015-09-01 00:39
Absolutely makes perfect sense. The current FOXML in its entirety is
migrated as an archival datastream and so all of that data is preserved and
available.

Sent from my iPhone

On Aug 31, 2015, at 6:19 PM, Sonya Betz <notifications@github.com> wrote:

Follow up from conversation with Leah - she wanted to ensure that we
maintain (either in the item record, or other place in metadata)
information about the time and date of an item's original upload to ERA.
Based on what I see in Hydra item record, the date of upload is the date of
migration into Hydra and not the date the item was originally added to ERA
(which will predate migration for all items that are migrated). Can anyone
advise on if / how that metadata is retained?

Also important for Leah was maintaining the record of thesis workflow
transactions (eg date thesis was submitted, revised, archived, and by whom
etc). Will that information also be migrated?

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/574>.

**Comment by pbinkley** [comment] 2015-09-01 14:51
Yes, this has to happen. I think the implementation will be slightly tricky
since that's not a field that Hydra expects to be set by any process other
than its own. I wonder whether we'll have to add an extra date field for
era-ingest-date, and arrange to use this for things like OAI requests.
We'll look into this.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by umarqasim** [comment] 2015-09-01 22:18
Thanks Peter for looking into this. This information is important to retain
as it supports authenticity and provenance piece in long term preservation.

*--*
*Umar Qasim, PhD*
Digital Preservation Officer
2-10N Cameron Library | University of Alberta
Edmonton, Alberta T6G 2J8, Canada
Tel: 780-492-9861 | Fax: 780-492-9243
umar.qasim@ualberta.ca | http://www.umarqasim.ca

**Comment by pbinkley** [comment] 2015-09-02 20:10
Now that I look into this, I think we may already be ok: I'm not seeing the problem that @sfbetz saw. E.g. on plano at the moment: http://plano.library.ualberta.ca/files/vm40xr68c#.VedVm7My3mF . The uploaded and last-modified dates are from 2013 and 2014, and correspond to what shows in ERA for this item: https://era.library.ualberta.ca/public/view/item/uuid:99d9c24d-bbaf-4afd-af33-5677e59eaffe (you have to be logged in as admin to see them, and click on the workflow history to see the deposit date). Sonya, can you share the item that triggered this concern? (I hope we haven't deleted it in our work on plano this week.)
It remains to be confirmed that the right date will be used by the OAI server to discover new and changed records based on timestamp.

**Comment by sfbetz** [comment] 2015-09-02 20:33
My bad, I was looking at a series of photographs that were all uploaded on the same day in January and didn't check them in legacy ERA.  So yes. Looks like the feature is there. Thanks for a more thorough and careful inspection, @pbinkley !

**Comment by sfarnel** [comment] 2015-09-02 20:39
:)

On Wed, Sep 2, 2015 at 2:33 PM, Sonya Betz <notifications@github.com> wrote:

> My bad, I was looking at a series of photographs that were all uploaded on
> the same day in January and didn't check them in legacy ERA. So yes. Looks
> like the feature is there. Thanks for a more thorough and careful
> inspection, @pbinkley <https://github.com/pbinkley> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/574#issuecomment-137236478>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment] 2015-09-02 22:16
OK, I'll close this, but we should be aware of the question as we do the OAI implementation #570

**Closed by pbinkley** 2015-09-02 22:16 UTC
Labels: question
